kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc-ebs
  labels:
    type: ebs
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: mongo-volume-ebs